const teacherdata = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    password: "john123",
    mobileNumber: "1234567890",
    address: "123 Main St, City",
    hoursMeetTaken: 50,
    ordersCount: 800,
    experience: "7 years",
    areaOfInterest: "Mathematics",
    rate: 50,
    rating: 4.5,
    userReviews: ["Great teacher!", "Very knowledgeable"],
    videoCallAvailability: true,
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    description: "Mathematics Tutor / Experienced / Patient",
    hourlyRate: 50,
  },
  {
    id: 2,
    name: "Alice Smith",
    email: "alice.smith@example.com",
    password: "alice123",
    mobileNumber: "9876543210",
    address: "456 Oak St, Town",
    hoursMeetTaken: 30,
    ordersCount: 1200,
    experience: "4 years",
    areaOfInterest: "English Literature",
    rate: 60,
    rating: 4.2,
    userReviews: ["Excellent tutor!", "Helped me a lot"],
    videoCallAvailability: false,
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    description: "English Literature Tutor / Writer / Book Enthusiast",
    hourlyRate: 60,
  },
  {
    id: 3,
    name: "Bob Johnson",
    email: "bob.johnson@example.com",
    password: "bob123",
    mobileNumber: "5556667777",
    address: "789 Pine St, Village",
    hoursMeetTaken: 40,
    ordersCount: 600,
    experience: "9 years",
    areaOfInterest: "Physics",
    rate: 55,
    rating: 4.8,
    userReviews: ["Great at explaining concepts", "Passionate about physics"],
    videoCallAvailability: true,
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    description: "Physics Tutor / Researcher / Science Geek",
    hourlyRate: 55,
  },
  {
    id: 4,
    name: "Eva Brown",
    email: "eva.brown@example.com",
    password: "eva123",
    mobileNumber: "3332221111",
    address: "101 Cedar St, Suburb",
    hoursMeetTaken: 20,
    ordersCount: 1500,
    experience: "2 years",
    areaOfInterest: "Biology",
    rate: 70,
    rating: 4.0,
    userReviews: ["Knowledgeable in biology", "Clear explanations"],
    videoCallAvailability: true,
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    description: "Programming Tutor / Web Developer / Coding Enthusiast",
    hourlyRate: 70,
  },
  {
    id: 5,
    name: "Charlie Wilson",
    email: "charlie.wilson@example.com",
    password: "charlie123",
    mobileNumber: "9998887777",
    address: "202 Elm St, County",
    hoursMeetTaken: 25,
    ordersCount: 1000,
    experience: "6 years",
    areaOfInterest: "History",
    rate: 65,
    rating: 4.6,
    userReviews: ["Passionate about history", "Engaging lessons"],
    videoCallAvailability: false,
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    description: "History Tutor / Historian / Storyteller",
    hourlyRate: 65,
  },
  {
    id: 6,
    name: "Grace Miller",
    email: "grace.miller@example.com",
    password: "grace123",
    mobileNumber: "7776665555",
    address: "303 Maple St, State",
    hoursMeetTaken: 45,
    ordersCount: 900,
    experience: "8 years",
    areaOfInterest: "Chemistry",
    rate: 58,
    rating: 4.7,
    userReviews: ["Passionate about chemistry", "Clear and concise teaching"],
    videoCallAvailability: true,
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    description: "Chemistry Tutor / Lab Scientist / Analytical Thinker",
    hourlyRate: 58,
  },
  {
    id: 7,
    name: "David Davis",
    email: "david.davis@example.com",
    password: "david123",
    mobileNumber: "4445556666",
    address: "404 Walnut St, Province",
    hoursMeetTaken: 35,
    ordersCount: 1100,
    experience: "3 years",
    areaOfInterest: "Languages",
    rate: 55,
    rating: 4.1,
    userReviews: ["Polyglot tutor", "Cultural insights"],
    videoCallAvailability: false,
    image: "https://randomuser.me/api/portraits/men/7.jpg",
    description: "Language Tutor / Polyglot / Cultural Enthusiast",
    hourlyRate: 55,
  },
  {
    id: 8,
    name: "Olivia White",
    email: "olivia.white@example.com",
    password: "olivia123",
    mobileNumber: "6667778888",
    address: "505 Birch St, Territory",
    hoursMeetTaken: 55,
    ordersCount: 1300,
    experience: "5 years",
    areaOfInterest: "Art",
    rate: 75,
    rating: 4.9,
    userReviews: ["Talented artist", "Inspires creativity"],
    videoCallAvailability: true,
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    description: "Art Tutor / Painter / Creative Soul",
    hourlyRate: 75,
  },
  {
    id: 9,
    name: "Samuel Green",
    email: "samuel.green@example.com",
    password: "samuel123",
    mobileNumber: "2223334444",
    address: "606 Pine St, Region",
    hoursMeetTaken: 28,
    ordersCount: 700,
    experience: "1 year",
    areaOfInterest: "Music",
    rate: 68,
    rating: 3.8,
    userReviews: ["Talented pianist", "Melodious sessions"],
    videoCallAvailability: true,
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    description: "Music Tutor / Pianist / Melody Maker",
    hourlyRate: 68,
  },
  {
    id: 10,
    name: "Sophia Black",
    email: "sophia.black@example.com",
    password: "sophia123",
    mobileNumber: "1112223333",
    address: "707 Oak St, District",
    hoursMeetTaken: 32,
    ordersCount: 950,
    experience: "10 years",
    areaOfInterest: "Fitness",
    rate: 80,
    rating: 5.0,
    userReviews: ["Dedicated fitness trainer", "Promotes a healthy lifestyle"],
    videoCallAvailability: true,
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    description: "Fitness Tutor / Personal Trainer / Health Advocate",
    hourlyRate: 80,
  },
  {
    id: 11,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    password: "michael123",
    mobileNumber: "8889990000",
    address: "808 Oak St, Suburb",
    hoursMeetTaken: 22,
    ordersCount: 850,
    experience: "3.5 years",
    areaOfInterest: "Computer Science",
    rate: 65,
    rating: 4.3,
    userReviews: ["Expert in programming", "Great coding mentor"],
    videoCallAvailability: true,
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    description: "Computer Science Tutor / Software Developer / Coding Mentor",
    hourlyRate: 65,
  },
  {
    id: 12,
    name: "Emma Taylor",
    email: "emma.taylor@example.com",
    password: "emma123",
    mobileNumber: "3334445555",
    address: "909 Pine St, City",
    hoursMeetTaken: 18,
    ordersCount: 1200,
    experience: "6 years",
    areaOfInterest: "Literature",
    rate: 55,
    rating: 4.7,
    userReviews: ["Passionate about literature", "Inspires a love for books"],
    videoCallAvailability: false,
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    description: "Literature Tutor / Bookworm / Literary Enthusiast",
    hourlyRate: 55,
  },
];

export default teacherdata;
