const tutorProfiles = [
  {
    id: 1,
    name: "John Doe",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    orders: 800,
    description: "Mathematics Tutor / Experienced / Patient",
    hourlyRate: 50,
  },
  {
    id: 2,
    name: "Alice Smith",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    orders: 1200,
    description: "English Literature Tutor / Writer / Book Enthusiast",
    hourlyRate: 60,
  },
  {
    id: 3,
    name: "Bob Johnson",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    orders: 600,
    description: "Physics Tutor / Researcher / Science Geek",
    hourlyRate: 55,
  },
  {
    id: 4,
    name: "Eva Brown",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    orders: 1500,
    description: "Programming Tutor / Web Developer / Coding Enthusiast",
    hourlyRate: 70,
  },
  {
    id: 5,
    name: "Charlie Wilson",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    orders: 1000,
    description: "History Tutor / Historian / Storyteller",
    hourlyRate: 65,
  },
  {
    id: 6,
    name: "Grace Miller",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    orders: 900,
    description: "Chemistry Tutor / Lab Scientist / Analytical Thinker",
    hourlyRate: 58,
  },
  {
    id: 7,
    name: "David Davis",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
    orders: 1100,
    description: "Language Tutor / Polyglot / Cultural Enthusiast",
    hourlyRate: 55,
  },
  {
    id: 8,
    name: "Olivia White",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    orders: 1300,
    description: "Art Tutor / Painter / Creative Soul",
    hourlyRate: 75,
  },
  {
    id: 9,
    name: "Samuel Green",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
    orders: 700,
    description: "Music Tutor / Pianist / Melody Maker",
    hourlyRate: 68,
  },
  {
    id: 10,
    name: "Sophia Black",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    orders: 950,
    description: "Fitness Tutor / Personal Trainer / Health Advocate",
    hourlyRate: 80,
  },
];

export default tutorProfiles;
